# SITE CONFIGURATION
baseurl: ""
url: "https://missionpinball.github.io"
title: Mission Pinball Framework Blog
description: "Mission Pinball Framework Blog"

collections:
  events:
    output: true
    permalink: /event/:name.html
  projects:
    output: true
    permalink: /project/:name.html
  hardware_platforms:
    output: true
    permalink: /hardware_platform/:name.html

future: true

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "events"
    values:
      layout: event
  - scope:
      path: ""
      type: "hardware_platforms"
    values:
      layout: hardware_platform
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
